# Site
title: "Blog Page"
subtitle: ""
description: ""
author: ""
language: "en"
timezone: ""

# URL
url: http://yoursite.com
root: "/"

# Director
pages_dir: ""
posts_dir: ""
src_dir: ""

# Pagination
# Set per_page to 0 to disable pagination
per_page: 10

# Extension
theme: ""