# Site
title: "Blog Page"
subtitle: ""
description: ""
author: ""
language: "en"
timezone: ""

# URL
url: http://yoursite.com # Web site url
root: "/" # Path/to/root

# Director
pages_dir: "pages/"
posts_dir: "posts/"
src_dir: "src/"

# Pagination
# Set per_page to 0 to disable pagination
per_page: 10

# Extension
theme: ""