# Site
title: "Blog Page"
subtitle: ""
description: ""
author: "JKol"
language: "en"
timezone: ""

# URL
url: http://yoursite.com
root: "/github/blogpage/"

# Director
pages_dir: "pages/"
posts_dir: "posts/"
src_dir: "src/"

# Pagination
# Set per_page to 0 to disable pagination
per_page: 10

# Extension
theme: ""