# Site
title: "Blog Page"
subtitle: ""
description: ""
author: ""
language: "en"
timezone: ""

# URL
url: http://yoursite.com
root: "/"

# Director
source_dir: ""
public_dir: ""
tag_dir: ""
archive_dir: ""
category_dir: ""
code_dir: ""

# Pagination
# Set per_page to 0 to disable pagination
per_page: 10

# Extension
theme: ""